#%RAML 1.0 Library
usage: |
  Use to define some ORM-specific constructs.

annotationTypes:
  id:
  indexed:
    parameters:
      value:
        type: boolean
        required: false
  ref:
    parameters:
      value:
        type: string
        required: false
