#%RAML 1.0 Library
usage: |
  Use to define some ORM-specific constructs.

annotationTypes:
  id:
    description: This field is an ID of the class
  indexed:
    description: Not sure we need this annotation
    parameters:
      value:
        type: boolean
        required: false
  transient:
    description: Transient property, never saved
    parameters:
      value:
        type: boolean
        required: false
  column:
    description: Manually specifies the column
    parameters:
      value:
        type: string
        required: false
  join:
    description: reference to other class/table
    parameters:
      value:
        type: string
        required: false
