#%RAML 1.0
title: Test Database
version: v0
baseUri: http://mydatabase.com/
displayName: My database
protocols: [HTTPS]

uses:
  orm: !include lib/orm.raml

types:
  Address:
    type: object
    displayName: An address (quite simple implementation)
    properties:
      id:
        type: number
        (orm.id):
      country: string
      city: string
      street: string
      house: string

  Person:
    type: object
    displayName: System's person
    properties:
      id:
        type: number
        (orm.id):
      firstName:
        type: string
        (orm.indexed): true
      lastName: string
      # homePhone: Phone
      # cellPhone: Phone
      addressId:
        type: number
        (orm.join): Address
        required: false
      yearOfBirth: number

  Pet:
    type: object
    displayName: Pet that can live at some address and have an owner
    properties:
      id:
        type: number
        (orm.id):
      owner:
        type: number
        (orm.join): person
      name:
        type: string
      addressId:
        type: number
        (orm.join): Address

/person:
  post:
    (orm.create.request): Person
    body:
      application/json:
        type: Person
    description: |
      Creates new person
    responses:
      200:
        body:
          application/json:
            type: Person
  get:
    (orm.list.request): Person
    description: |
      Returns persons list
    responses:
      200:
        body:
          application/json:
            type: Person[]
  /{personId}:
    uriParameters:
       personId:
         (orm.join): Person
         type: number
    get:
      (orm.get.request): Person
      description: |
        Get the person
      responses:
        200:
          body:
            application/json:
              type: Person

    delete:
      (orm.delete.request): Person
      description: |
        Delete the person
      responses:
        200:
          body:
