#%RAML 1.0
title: Test Database
version: v0
baseUri: http://mydatabase.com/
displayName: My database
protocols: [HTTPS]

uses:
  orm: !include lib/orm.raml

types:
  Phone:
    type: object
    properties:
      code: string
      number: string

  Address:
    type: object
    displayName: An address (quite simple implementation)
    properties:
      id:
        type: number
        (orm.id):
      country: string
      city: string
      street: string
      house: string

  User:
    type: object
    displayName: System's user
    properties:
      id:
        type: number
        (orm.id):
      firstName:
        type: string
        (orm.indexed): true
      lastName: string
      homePhone: Phone
      cellPhone: Phone
      addressId:
        type: number
        (orm.ref): Address
        required: false

  Pet:
    type: object
    displayName: Pet that can live at some address and have an owner
    properties:
      id:
        type: number
        (orm.id):
      owner:
        type: number
        (orm.ref): User
      name:
        type: string
      addressId:
        type: number
        (orm.ref): Address

/user/create:
  post:
    description: |
      Creates new user
    responses:
      200:
        body:
          application/json:
            type: User
